server:
  port: 8083
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: safipay-super-secret-key-for-jwt-signing-must-be-256-bits-long
services:
  wallet-service-url: http://localhost:8082
  fraud-service-url: http://localhost:8087
  ledger-service-url: http://localhost:8085
