import { Injectable } from '@angular/core';

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

import {
  CheckoutResponse,
  MerchantOrderReceipt
} from './checkout.models';

@Injectable({
  providedIn: 'root'
})
export class ReceiptPdfService {


  downloadOverall(
    receipt: CheckoutResponse
  ): void {

    const pdf =
      new jsPDF();


    pdf.setFontSize(22);

    pdf.text(
      'SafiPay',
      14,
      20
    );


    pdf.setFontSize(15);

    pdf.text(
      'Marketplace Receipt',
      14,
      30
    );


    pdf.setFontSize(9);

    pdf.text(
      `Checkout ID: ${receipt.checkoutId}`,
      14,
      42
    );


    pdf.text(
      `Status: ${receipt.status}`,
      14,
      49
    );


    pdf.text(
      `Date: ${this.formatDate(receipt.createdAt)}`,
      14,
      56
    );


    autoTable(
      pdf,
      {

        startY: 67,

        head: [[
          'Merchant',
          'Items',
          'Status',
          'Amount'
        ]],

        body:
          receipt.merchantOrders.map(
            order => [

              order.merchantName,

              order.items
                .reduce(
                  (sum, item) =>
                    sum + item.quantity,
                  0
                )
                .toString(),

              order.status,

              this.money(
                order.totalAmount
              )
            ]
          )
      }
    );


    const finalY =
      (pdf as any)
        .lastAutoTable
        ?.finalY ?? 100;


    pdf.setFontSize(14);

    pdf.text(
      `Total: ${this.money(receipt.grandTotal)}`,
      14,
      finalY + 16
    );


    pdf.setFontSize(8);

    pdf.text(
      'Generated by SafiPay',
      14,
      finalY + 27
    );


    pdf.save(
      `safipay-receipt-${receipt.checkoutId.substring(0, 8)}.pdf`
    );
  }


  downloadMerchant(
    receipt: CheckoutResponse,
    order: MerchantOrderReceipt
  ): void {

    const pdf =
      new jsPDF();


    pdf.setFontSize(22);

    pdf.text(
      'SafiPay',
      14,
      20
    );


    pdf.setFontSize(15);

    pdf.text(
      order.merchantName,
      14,
      31
    );


    pdf.setFontSize(9);

    pdf.text(
      `Order ID: ${order.orderId}`,
      14,
      43
    );


    pdf.text(
      `Checkout ID: ${receipt.checkoutId}`,
      14,
      50
    );


    pdf.text(
      `Payment ID: ${order.paymentId ?? 'N/A'}`,
      14,
      57
    );


    pdf.text(
      `Date: ${this.formatDate(receipt.createdAt)}`,
      14,
      64
    );


    autoTable(
      pdf,
      {

        startY: 75,

        head: [[
          'Item',
          'Type',
          'Qty',
          'Price',
          'Subtotal'
        ]],

        body:
          order.items.map(
            item => [

              item.title,

              item.type,

              item.quantity.toString(),

              this.money(
                item.unitPrice
              ),

              this.money(
                item.subtotal
              )
            ]
          )
      }
    );


    const finalY =
      (pdf as any)
        .lastAutoTable
        ?.finalY ?? 110;


    pdf.setFontSize(14);

    pdf.text(
      `Total: ${this.money(order.totalAmount)}`,
      14,
      finalY + 16
    );


    pdf.setFontSize(8);

    pdf.text(
      'Generated by SafiPay',
      14,
      finalY + 27
    );


    pdf.save(
      `safipay-${this.safeName(order.merchantName)}-${order.orderId.substring(0, 8)}.pdf`
    );
  }


  private money(
    value: number
  ): string {

    return `R${Number(value).toFixed(2)}`;
  }


  private formatDate(
    date: string | null
  ): string {

    if (!date) {
      return 'N/A';
    }

    return new Date(
      date
    ).toLocaleString();
  }


  private safeName(
    value: string
  ): string {

    return value
      .toLowerCase()
      .replace(
        /[^a-z0-9]+/g,
        '-'
      )
      .replace(
        /^-+|-+$/g,
        ''
      );
  }
}