server:
  port: 8084

spring:
  application:
    name: stokvel-service

  datasource:
    url: jdbc:postgresql://postgres:5432/safipay_stokvel
    driver-class-name: org.postgresql.Driver
    username: rethabile
    password: password123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: safipay-super-secret-key-for-jwt-signing-must-be-256-bits-long

services:
  wallet-service-url: ${WALLET_SERVICE_URL:http://localhost:8082}
  fraud-service-url: ${FRAUD_SERVICE_URL:http://localhost:8087}
  ledger-service-url: ${LEDGER_SERVICE_URL:http://localhost:8085}