server:
  port: 8088
spring:
  application:
    name: webhook-service
  # datasource:
  #   url: jdbc:h2:mem:webhookdb;DB_CLOSE_DELAY=-1
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: create-drop
  #   show-sql: false
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  datasource:
    url: jdbc:postgresql://postgres:5432/safipay_webhook
    driver-class-name: org.postgresql.Driver
    username: rethabile
    password: password123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: safipay-super-secret-key-for-jwt-signing-must-be-256-bits-long
webhook:
  max-retry-attempts: 3
  retry-delay-seconds: 30
  timeout-seconds: 10
  signature-header: X-SafiPay-Signature
logging:
  level:
    com.safipay.webhook: DEBUG
